/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package doublependulum;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.text.html.StyleSheet;

/**
 *
 * @author Kyungbin
 */
public class Selection extends javax.swing.JFrame {

     
    public Selection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        createButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kyungbin\\Downloads\\GraphicDesign (1).png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSpinner1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(40, 40, 100, 5));
        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSpinner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner1MouseClicked(evt);
            }
        });
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 150, 60));

        jSpinner2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(30, 30, 100, 5));
        jSpinner2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSpinner2.setFocusTraversalPolicyProvider(true);
        jSpinner2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner2MouseClicked(evt);
            }
        });
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 150, 60));

        jSpinner4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(30, 30, 100, 5));
        jSpinner4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSpinner4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner4MouseClicked(evt);
            }
        });
        getContentPane().add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 150, 60));

        jSpinner5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(50, 50, 85, 5));
        jSpinner5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSpinner5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner5MouseClicked(evt);
            }
        });
        getContentPane().add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 150, 60));

        createButton.setBackground(new java.awt.Color(255, 102, 102));
        createButton.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Create!");
        createButton.setBorder(null);
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
        });
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 230, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kyungbin\\Downloads\\GraphicDesign (3).png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -50, 610, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        
    }//GEN-LAST:event_createButtonActionPerformed

    private void jSpinner4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner4MouseClicked
  

    }//GEN-LAST:event_jSpinner4MouseClicked

    private void jSpinner2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner2MouseClicked
        
        
    }//GEN-LAST:event_jSpinner2MouseClicked

    private void jSpinner1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseClicked
        
    }//GEN-LAST:event_jSpinner1MouseClicked

    private void jSpinner5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner5MouseClicked
        
    }//GEN-LAST:event_jSpinner5MouseClicked

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked
        
        
        //CREATES DOUBLE PENDULUM OBJECT
        DoublePendulum dp = new DoublePendulum();
        
        //ASSIGNS THE VALUES FROM THE USE INPUT TO THE TWO MASSES AND LENGTHS 
        dp.m1 = (int) jSpinner4.getValue();
        dp.m2 = (int) jSpinner2.getValue();
        dp.l1 = (int) jSpinner1.getValue();
        dp.l2 = (int) jSpinner5.getValue();
        
       
     //MAKING A GUI SCREEN 
        dp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dp.setTitle("Double Pendulum");
        dp.setBackground(Color.blue);
        dp.setSize(700, 700);

        //SETS IT TO VISIBLE, ASSIGNS THE NUMBER OF FRAMES AND UPDATE THE ANGLES 
        dp.setVisible(true);
        int numFrames = 500;
        dp.updateAngle(numFrames);
       
        //RUNS THE FOR LOOP TO KEEP ON DRAWING 
            for (int j = 0; j < numFrames; j++){
                dp.time = j;
                dp.paintComponent(dp.getGraphics());
                

            dp.sleep(20);
        
            }
        
    }//GEN-LAST:event_createButtonMouseClicked

    public static void sleep( int duration ) {
        try {
              Thread.sleep( duration );
            }
        catch (Exception e) {
            }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selection().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton createButton;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JSpinner jSpinner1;
    public javax.swing.JSpinner jSpinner2;
    public static javax.swing.JSpinner jSpinner4;
    public javax.swing.JSpinner jSpinner5;
    // End of variables declaration//GEN-END:variables
}
